#!/usr/bin/env python3
import os, json, datetime

ROOT = os.path.dirname(os.path.dirname(__file__))
DATA = os.path.join(ROOT, "data", "latest.json")
DOCS = os.path.join(ROOT, "docs")
os.makedirs(DOCS, exist_ok=True)

INDEX = os.path.join(DOCS, "index.html")
TARGET_JSON = os.path.join(DOCS, "latest.json")

def load_latest():
    try:
        with open(DATA, "r", encoding="utf-8") as f:
            return json.load(f)
    except Exception:
        return {"generated_at": "", "items": []}

def write_json(latest):
    with open(TARGET_JSON, "w", encoding="utf-8") as f:
        json.dump(latest, f, indent=2, ensure_ascii=False)

def write_index(latest):
    generated_at = latest.get("generated_at", "")
    html = f"""<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>OSINT Monitor — Non‑KEV Exploitation Activity</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <style>
    body{{font-family:system-ui,-apple-system,Segoe UI,Roboto,Helvetica,Arial,sans-serif;margin:2rem;background:#f9fafb;color:#0f172a}}
    header{{margin-bottom:1.5rem}}
    h1{{font-size:1.5rem;margin:0}}
    .meta{{color:#475569;margin-top:.25rem}}
    .controls{{margin:1rem 0;display:flex;gap:.5rem;flex-wrap:wrap}}
    input,select{{padding:.5rem;border:1px solid #cbd5e1;border-radius:.375rem}}
    table{{width:100%;border-collapse:collapse;margin-top:.75rem}}
    th,td{{padding:.5rem .6rem;border-bottom:1px solid #e2e8f0;vertical-align:top}}
    th{{text-align:left;background:#f1f5f9}}
    .claim{{display:inline-block;padding:.15rem .35rem;border-radius:.35rem;font-size:.8rem;border:1px solid #cbd5e1}}
    .claim-verified{{background:#ecfeff;border-color:#06b6d4}}
    .claim-likely{{background:#f0fdf4;border-color:#22c55e}}
    .claim-rumor{{background:#fffbeb;border-color:#f59e0b}}
    .claim-failed{{background:#fee2e2;border-color:#ef4444}}
    .claim-none{{background:#f8fafc;border-color:#cbd5e1}}
    footer{{margin-top:2rem;color:#475569;font-size:.9rem}}
    .small{{font-size:.9rem;color:#475569}}
    .link{{color:#0ea5e9;text-decoration:none}}
    .link:hover{{text-decoration:underline}}
  </style>
</head>
<body>
  <header>
    <h1>OSINT Monitor — Non‑KEV Exploitation Activity</h1>
    <div class="meta">Last updated: <span id="generatedAt">{generated_at}</span></div>
    <div class="small">This page lists public OSINT items that mention exploitation/POC/0‑day and are <strong>not</strong> already present in the CISA KEV catalog.</div>
  </header>

  <div class="controls">
    <input id="q" type="search" placeholder="Filter by text or CVE…" aria-label="Filter">
    <select id="claimFilter" aria-label="Claim filter">
      <option value="">All classifications</option>
      <option value="verified/active">verified/active</option>
      <option value="likely/poc">likely/poc</option>
      <option value="rumor">rumor</option>
      <option value="failed">failed</option>
      <option value="mention">mention</option>
      <option value="none">none</option>
    </select>
  </div>

  <table id="tbl">
    <thead>
      <tr>
        <th>Source</th>
        <th>Title</th>
        <th>Claim</th>
        <th>CVEs</th>
        <th>Link</th>
        <th>Published</th>
      </tr>
    </thead>
    <tbody></tbody>
  </table>

  <footer>
    <div>Tracking Issue: <a class="link" href="./issue.html">OSdiv>
    <div class="small">Note: Respect robots.txt/ToS for original sources. This page is auto‑generated by GitHub Actions.</div>
  </footer>

<script>
async function load(){
  const res = await fetch('latest.json',{cache:'no-store'});
  const data = await res.json();
  const items = data.items || [];
  const tbody = document.querySelector('#tbl tbody');

  function badge(c){
    const cls = c==='verified/active'?'claim claim-verified':
                c==='likely/poc'   ?'claim claim-likely':
                c==='rumor'        ?'claim claim-rumor':
                c==='failed'       ?'claim claim-failed':'claim claim-none';
    return `<span class="${cls}">${c||'none'}</span>`;
  }

  function row(it){
    const cves = (it.cves||[]).join(', ') || 'N/A';
    const pub  = it.published || '';
    const url  = it.url || '';
    const title = (it.title||'').replace(/</g,'&lt;');
    const src = (it.source||'').replace(/</g,'&lt;');
    return `<tr data-text="${[src,title,cves].join(' ').toLowerCase()}" data-claim="${(it.claim||'').toLowerCase()}">
      <td>${src}</td>
      <td>${title}</td>
      <td>${badge(it.claim||'none')}</td>
      <td>${cves}</td>
      <td>${url ? `<a class="link" href="${url}" target="_blank" rel="noopener">open</atbody.innerHTML = items.map(row).join('');

  const q = document.getElementById('q');
  const cf = document.getElementById('claimFilter');
  function applyFilter(){
    const qv = (q.value||'').toLowerCase();
    const cv = (cf.value||'').toLowerCase();
    [...tbody.querySelectorAll('tr')].forEach(tr=>{
      const okQ = tr.dataset.text.includes(qv);
      const okC = !cv || tr.dataset.claim===cv;
      tr.style.display = (okQ && okC) ? '' : 'none';
    });
  }
  q.addEventListener('input', applyFilter);
  cf.addEventListener('change', applyFilter);
}
load();
</script>
</body>
</html>
"""
    with open(INDEX, "w", encoding="utf-8") as f:
        f.write(html)

def main():
    latest = load_latest()
    # copy JSON so the page can fetch it from the same origin
    write_json(latest)
    write_index(latest)
    print(f"[pages] wrote {INDEX} and {TARGET_JSON}; items={len(latest.get('items', []))}")

if __name__ == "__main__":
    main()
